name: Run Tests

on:
  schedule:
    # Run at 12 AM daily
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger
    inputs:
      browser:
        description: 'Browser to run the tests on (default: chrome)'
        required: false
        default: 'chrome'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, edge, safari] # Define browsers to test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          BROWSER: ${{ matrix.browser }}
        run: |
          echo "Running tests on browser: $BROWSER"
          npm test
